import {
  AuditLogEntry,
  CivicEvent,
  Issue,
  Official,
  PollRecord,
  PromiseRecord,
  Town,
  UC,
  NGO,
  CommunityLeader,
} from "@/types/civic";

export const MOCK_TOWNS: Town[] = [
  {
    id: "town-gulshan",
    name: "Gulshan-e-Iqbal Town",
    slug: "gulshan-town",
    district: "East",
    totalUcs: 13,
    teamScore: 68.2,
    rank: 4,
    townChairmanName: "Dr. Fawad Ahmed",
    townChairmanPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    townChairmanParty: "Independent / Municipal Coalition",
  },
  {
    id: "town-jamshed",
    name: "Jamshed Town",
    slug: "jamshed-town",
    district: "East",
    totalUcs: 15,
    teamScore: 72.8,
    rank: 2,
    townChairmanName: "Zubair Hashmi",
    townChairmanPhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
    townChairmanParty: "Citizens United",
  },
  {
    id: "town-nazimabad",
    name: "Nazimabad Town",
    slug: "nazimabad-town",
    district: "Central",
    totalUcs: 11,
    teamScore: 74.5,
    rank: 1,
    townChairmanName: "Syed Rehan Ali",
    townChairmanPhoto: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
    townChairmanParty: "Karachi Civic Alliance",
  },
  {
    id: "town-korangi",
    name: "Korangi Town",
    slug: "korangi-town",
    district: "Korangi",
    totalUcs: 14,
    teamScore: 48.6,
    rank: 19,
    townChairmanName: "M. Aslam Khan",
    townChairmanPhoto: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&crop=face",
    townChairmanParty: "Public Welfare Party",
  },
];

export const MOCK_OFFICIAL_UC7: Official = {
  id: "off-faisal-siddiqui",
  name: "Faisal Siddiqui",
  slug: "faisal-siddiqui",
  seatTitle: "Chairman, UC-7 Gulshan",
  photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=240&h=240&fit=crop&crop=face",
  party: "Jamaat-e-Islami (JI)",
  officeContact: "021-34988712 · Block 13-C UC Office",
  termStart: "2023-06-15",
  termEnd: "2027-06-15",
  isClaimed: true,
  badges: ["Top 10% Responder", "Zero Stale Backlog", "Verified Office"],
  promisesKept: 5,
  promisesTotal: 6,
  eventsHeld: 4,
  thankYouCount: 142,
  fixSatisfaction: 4.6,
};

export const MOCK_UCS: UC[] = [
  {
    id: "uc-gulshan-7",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    number: 7,
    name: "UC-7 Gulshan (NIPA / Block 13)",
    slug: "gulshan-7",
    neighborhoods: ["Block 13-A", "Block 13-B", "Block 13-D", "NIPA Chowrangi", "Disco Bakery Area"],
    lat: 24.918,
    lng: 67.097,
    chairman: MOCK_OFFICIAL_UC7,
    score: 79.4,
    cityRank: 14,
    townRank: 1,
    trend30d: 4.2,
    totalEligibleIssues: 58,
    resolvedIssues: 46,
    oldestOpenDays: 14,
    hasEnoughData: true,
  },
  {
    id: "uc-gulshan-4",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    number: 4,
    name: "UC-4 Gulshan-e-Iqbal I (Civic Centre)",
    slug: "gulshan-4",
    neighborhoods: ["Civic Centre", "Hassan Square", "Expo Centre Area"],
    lat: 24.898,
    lng: 67.078,
    chairman: {
      id: "off-tariq-aziz",
      name: "Tariq Aziz",
      slug: "tariq-aziz",
      seatTitle: "Chairman, UC-4 Gulshan",
      photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face",
      party: "Karachi Democratic Front",
      officeContact: "021-34900112",
      termStart: "2023-06-15",
      termEnd: "2027-06-15",
      isClaimed: true,
      badges: ["Active Baithaks"],
      promisesKept: 3,
      promisesTotal: 5,
      eventsHeld: 2,
      thankYouCount: 78,
      fixSatisfaction: 4.1,
    },
    score: 66.8,
    cityRank: 44,
    townRank: 2,
    trend30d: 1.8,
    totalEligibleIssues: 42,
    resolvedIssues: 29,
    oldestOpenDays: 24,
    hasEnoughData: true,
  },
  {
    id: "uc-gulshan-6",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    number: 6,
    name: "UC-6 Gulshan (Block 6 & 7)",
    slug: "gulshan-6",
    neighborhoods: ["Block 6", "Block 7", "Moti Mahal Area"],
    lat: 24.912,
    lng: 67.086,
    chairman: {
      id: "off-imran-mehmood",
      name: "Imran Mehmood",
      slug: "imran-mehmood",
      seatTitle: "Chairman, UC-6 Gulshan",
      photo: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&h=200&fit=crop&crop=face",
      party: "Sindh Local Alliance",
      officeContact: "021-34988019",
      termStart: "2023-06-15",
      termEnd: "2027-06-15",
      isClaimed: false,
      badges: [],
      promisesKept: 2,
      promisesTotal: 4,
      eventsHeld: 1,
      thankYouCount: 45,
      fixSatisfaction: 3.8,
    },
    score: 62.4,
    cityRank: 68,
    townRank: 3,
    trend30d: -2.1,
    totalEligibleIssues: 38,
    resolvedIssues: 23,
    oldestOpenDays: 38,
    hasEnoughData: true,
  },
  {
    id: "uc-gulshan-2",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    number: 2,
    name: "UC-2 PIB Colony",
    slug: "pib-colony-2",
    neighborhoods: ["PIB Colony", "Nishtar Basti", "Jail Road"],
    lat: 24.891,
    lng: 67.054,
    chairman: {
      id: "off-nasir-hussain",
      name: "Nasir Hussain",
      slug: "nasir-hussain",
      seatTitle: "Chairman, UC-2 PIB Colony",
      photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&h=200&fit=crop&crop=face",
      party: "Independent",
      officeContact: "021-34120934",
      termStart: "2023-06-15",
      termEnd: "2027-06-15",
      isClaimed: true,
      badges: ["High Speed Resolution"],
      promisesKept: 4,
      promisesTotal: 5,
      eventsHeld: 3,
      thankYouCount: 92,
      fixSatisfaction: 4.3,
    },
    score: 58.7,
    cityRank: 95,
    townRank: 4,
    trend30d: 3.5,
    totalEligibleIssues: 31,
    resolvedIssues: 19,
    oldestOpenDays: 29,
    hasEnoughData: true,
  },
  {
    id: "uc-gulshan-3",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    number: 3,
    name: "UC-3 Essa Nagri",
    slug: "essa-nagri-3",
    neighborhoods: ["Essa Nagri", "Sir Shah Suleman Road", "Gharibabad Edge"],
    lat: 24.901,
    lng: 67.068,
    chairman: {
      id: "off-michael-masih",
      name: "Michael Masih",
      slug: "michael-masih",
      seatTitle: "Chairman, UC-3 Essa Nagri",
      photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
      party: "Minority Rights Civic Group",
      officeContact: "021-34812300",
      termStart: "2023-06-15",
      termEnd: "2027-06-15",
      isClaimed: false,
      badges: [],
      promisesKept: 1,
      promisesTotal: 4,
      eventsHeld: 0,
      thankYouCount: 19,
      fixSatisfaction: 2.9,
    },
    score: 38.2,
    cityRank: 218,
    townRank: 5,
    trend30d: -5.4,
    totalEligibleIssues: 46,
    resolvedIssues: 14,
    oldestOpenDays: 68,
    hasEnoughData: true,
  },
];

export const MOCK_ISSUES: Issue[] = [
  {
    id: "K-10492",
    ucId: "uc-gulshan-7",
    ucName: "UC-7 Gulshan (NIPA / Block 13)",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    categoryId: "drains",
    categoryName: "Drains & Sewerage",
    subCategory: "Overflowing Gutter",
    title: "Gutter overflowing into marketplace outside Disco Bakery",
    description: "Sewerage water has entered shops and main pedestrian walkway. Customers cannot walk and smell is unbearable.",
    lat: 24.9192,
    lng: 67.0984,
    addressApprox: "Service Lane opposite Disco Bakery, Block 13-D",
    gpsAccuracyMeters: 14,
    severity: "dangerous",
    isAnonymous: false,
    reporterName: "Zain Bawa",
    reporterId: "user-101",
    status: "marked_resolved",
    createdAt: "2026-09-21T10:15:00Z",
    updatedAt: "2026-09-24T14:30:00Z",
    daysOpen: 3,
    eligible: true,
    affectedCount: 38,
    weightedAffected: 42.5,
    isUserAffected: true,
    photos: [
      {
        id: "p-1",
        kind: "report",
        url: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=600&fit=crop",
        capturedAt: "2026-09-21T10:14:00Z",
        lat: 24.9192,
        lng: 67.0984,
        uploaderName: "Zain Bawa",
      },
    ],
    afterPhotos: [
      {
        id: "p-after-1",
        kind: "after",
        url: "https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=800&h=600&fit=crop",
        capturedAt: "2026-09-24T14:28:00Z",
        lat: 24.9191,
        lng: 67.0985,
        uploaderName: "UC-7 Sanitation Team",
      },
    ],
    officialResponse: {
      officialId: "off-faisal-siddiqui",
      officialName: "Faisal Siddiqui",
      seatTitle: "Chairman, UC-7 Gulshan",
      respondedAt: "2026-09-22T08:00:00Z",
      message: "UC suction machine dispatched with municipal sanitary workers. Drain line desilted and water cleared. Concrete ring resealed.",
      statusUpdate: "marked_resolved",
    },
    confirmationWindow: {
      markedResolvedAt: "2026-09-24T14:30:00Z",
      expiresAt: "2026-10-01T14:30:00Z",
      fixedVotes: 14,
      notFixedVotes: 1,
      userVoted: undefined,
    },
  },
  {
    id: "K-10448",
    ucId: "uc-gulshan-7",
    ucName: "UC-7 Gulshan (NIPA / Block 13)",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    categoryId: "streets",
    categoryName: "Streets & Paving",
    subCategory: "Massive Potholes",
    title: "Deep pothole cluster damaging vehicles on University Road slip",
    description: "Multiple cars and bikes bottom out daily. Monsoon rain made the crater 1.5 feet deep. Accidents happening every evening.",
    lat: 24.9214,
    lng: 67.0955,
    addressApprox: "University Road turn toward NIPA Bridge, Block 13-A",
    gpsAccuracyMeters: 8,
    severity: "dangerous",
    isAnonymous: false,
    reporterName: "Dr. Hammad Rizvi",
    reporterId: "user-104",
    status: "in_progress",
    createdAt: "2026-09-18T16:20:00Z",
    updatedAt: "2026-09-23T11:00:00Z",
    daysOpen: 6,
    eligible: true,
    affectedCount: 64,
    weightedAffected: 71.0,
    isUserAffected: true,
    photos: [
      {
        id: "p-2",
        kind: "report",
        url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&h=600&fit=crop",
        capturedAt: "2026-09-18T16:19:00Z",
        lat: 24.9214,
        lng: 67.0955,
        uploaderName: "Dr. Hammad Rizvi",
      },
    ],
    officialResponse: {
      officialId: "off-faisal-siddiqui",
      officialName: "Faisal Siddiqui",
      seatTitle: "Chairman, UC-7 Gulshan",
      respondedAt: "2026-09-19T09:30:00Z",
      message: "Town Road Dept contractor mobilised with cold-mix asphalt and heavy roller. Leveling scheduled over the weekend.",
      statusUpdate: "in_progress",
    },
  },
  {
    id: "K-10390",
    ucId: "uc-gulshan-7",
    ucName: "UC-7 Gulshan (NIPA / Block 13)",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    categoryId: "garbage",
    categoryName: "Garbage & Sanitation",
    subCategory: "Unlifted Dump",
    title: "Large open garbage dump accumulating near Millennium boundary",
    description: "Solid waste hasn't been lifted for 12 days. Garbage burning at night produces choking smoke for nearby apartments.",
    lat: 24.9145,
    lng: 67.1021,
    addressApprox: "Corner plot near Al-Mustafa Hospital road, Block 13-B",
    gpsAccuracyMeters: 12,
    severity: "normal",
    isAnonymous: true,
    reporterName: "Resident of UC-7",
    reporterId: "user-anon",
    status: "open",
    createdAt: "2026-09-12T07:45:00Z",
    updatedAt: "2026-09-12T07:45:00Z",
    daysOpen: 12,
    eligible: true,
    affectedCount: 51,
    weightedAffected: 55.4,
    isUserAffected: false,
    photos: [
      {
        id: "p-3",
        kind: "report",
        url: "https://images.unsplash.com/photo-1605600659908-0ef719419d41?w=800&h=600&fit=crop",
        capturedAt: "2026-09-12T07:44:00Z",
        lat: 24.9145,
        lng: 67.1021,
      },
    ],
  },
  {
    id: "K-10211",
    ucId: "uc-gulshan-7",
    ucName: "UC-7 Gulshan (NIPA / Block 13)",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    categoryId: "streetlights",
    categoryName: "Streetlights",
    subCategory: "Dead Bulbs",
    title: "8 consecutive streetlights dark along residential street 4",
    description: "Entire residential street completely blacked out for three weeks. Snatching incident reported two nights ago.",
    lat: 24.9175,
    lng: 67.0941,
    addressApprox: "Street 4, Sector 13-A, near Jamia Masjid",
    gpsAccuracyMeters: 10,
    severity: "normal",
    isAnonymous: false,
    reporterName: "Usman Ghani",
    reporterId: "user-112",
    status: "confirmed",
    createdAt: "2026-09-02T20:10:00Z",
    updatedAt: "2026-09-08T18:00:00Z",
    daysOpen: 6,
    eligible: true,
    affectedCount: 29,
    weightedAffected: 32.0,
    isUserAffected: false,
    photos: [
      {
        id: "p-4",
        kind: "report",
        url: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&h=600&fit=crop",
        capturedAt: "2026-09-02T20:08:00Z",
        lat: 24.9175,
        lng: 67.0941,
        uploaderName: "Usman Ghani",
      },
    ],
    afterPhotos: [
      {
        id: "p-4-after",
        kind: "after",
        url: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=800&h=600&fit=crop",
        capturedAt: "2026-09-07T21:00:00Z",
        lat: 24.9175,
        lng: 67.0941,
        uploaderName: "UC-7 Electrician Team",
      },
    ],
    officialResponse: {
      officialId: "off-faisal-siddiqui",
      officialName: "Faisal Siddiqui",
      seatTitle: "Chairman, UC-7 Gulshan",
      respondedAt: "2026-09-03T11:00:00Z",
      message: "8 new 100W energy saver LED fixtures installed and cable fault repaired.",
      statusUpdate: "confirmed",
    },
    confirmationWindow: {
      markedResolvedAt: "2026-09-07T21:00:00Z",
      expiresAt: "2026-09-14T21:00:00Z",
      fixedVotes: 22,
      notFixedVotes: 0,
      userVoted: "fixed",
    },
  },
  {
    id: "K-10512",
    ucId: "uc-gulshan-7",
    ucName: "UC-7 Gulshan (NIPA / Block 13)",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    categoryId: "drains",
    categoryName: "Drains & Sewerage",
    subCategory: "Missing Manhole Cover",
    title: "Open manhole in front of Government Primary School",
    description: "Dangerous open hole directly where school children walk. Someone put a tree branch in it as warning.",
    lat: 24.9205,
    lng: 67.0968,
    addressApprox: "Opposite Govt Primary School, Street 9, Block 13-B",
    gpsAccuracyMeters: 6,
    severity: "dangerous",
    isAnonymous: false,
    reporterName: "Mariam Sohail",
    reporterId: "user-128",
    status: "open",
    createdAt: "2026-09-24T08:15:00Z",
    updatedAt: "2026-09-24T08:15:00Z",
    daysOpen: 1,
    eligible: true,
    affectedCount: 76,
    weightedAffected: 88.2,
    isUserAffected: true,
    photos: [
      {
        id: "p-5",
        kind: "report",
        url: "https://images.unsplash.com/photo-1584467735871-8e85353a8413?w=800&h=600&fit=crop",
        capturedAt: "2026-09-24T08:14:00Z",
        lat: 24.9205,
        lng: 67.0968,
        uploaderName: "Mariam Sohail",
      },
    ],
  },
  {
    id: "K-10180",
    ucId: "uc-gulshan-3",
    ucName: "UC-3 Essa Nagri",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    categoryId: "drains",
    categoryName: "Drains & Sewerage",
    subCategory: "Blocked Nala",
    title: "Severe black sewage overflow throughout street 14",
    description: "Nala has been clogged for over 2 months. Contaminated water backing up into residential house entrances.",
    lat: 24.9015,
    lng: 67.0688,
    addressApprox: "Street 14, Christian Colony, Essa Nagri",
    gpsAccuracyMeters: 15,
    severity: "dangerous",
    isAnonymous: false,
    reporterName: "Daniel Gill",
    reporterId: "user-201",
    status: "open",
    createdAt: "2026-07-22T14:00:00Z",
    updatedAt: "2026-07-22T14:00:00Z",
    daysOpen: 64, // Over 30 days backlog!
    eligible: true,
    affectedCount: 112,
    weightedAffected: 124.0,
    isUserAffected: false,
    photos: [
      {
        id: "p-6",
        kind: "report",
        url: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=600&fit=crop",
        capturedAt: "2026-07-22T13:58:00Z",
        lat: 24.9015,
        lng: 67.0688,
      },
    ],
  },
];

export const MOCK_EVENTS: CivicEvent[] = [
  {
    id: "ev-1",
    title: "Sunday Community Cleaning Drive & Tree Plantation",
    type: "community_action",
    date: "Sunday, Sep 28, 2026",
    time: "08:00 AM - 11:30 AM",
    locationName: "Block 13-D Family Park, Gulshan",
    ucId: "uc-gulshan-7",
    ucName: "UC-7 Gulshan",
    organizerName: "UC-7 Welfare & Youth Committee",
    organizerRole: "Resident & Official Coalition",
    description: "Residents and UC volunteers will clear plastic debris, install 20 saplings, and repaint boundary benches. Tools provided.",
    rsvpCount: 84,
    isUserRsvpd: true,
    isVerified: true,
    proofPhotos: [
      "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=600&h=400&fit=crop",
    ],
  },
  {
    id: "ev-2",
    title: "Monsoon Drainage Preparedness Open Baithak",
    type: "uc_baithak",
    date: "Tuesday, Sep 30, 2026",
    time: "06:30 PM - 08:30 PM",
    locationName: "UC-7 Office Ground Hall, Block 13-C",
    ucId: "uc-gulshan-7",
    ucName: "UC-7 Gulshan",
    organizerName: "Faisal Siddiqui (Chairman UC-7)",
    organizerRole: "UC Chairman",
    description: "Public accountability discussion on nala de-silting, emergency sucker pumps, and low-lying street drainage plan.",
    rsvpCount: 47,
    isUserRsvpd: false,
    isVerified: true,
  },
];

export const MOCK_PROMISES: PromiseRecord[] = [
  {
    id: "prom-1",
    officialId: "off-faisal-siddiqui",
    officialName: "Faisal Siddiqui",
    ucName: "UC-7 Gulshan",
    text: "Convert 60 broken sodium streetlights into energy-efficient LEDs in Block 13-A and 13-B.",
    source: "UC-7 Inaugural Baithak Record #B-01",
    dateMade: "2026-06-18",
    dueDate: "2026-08-31",
    status: "kept",
    proofPhoto: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=600&h=400&fit=crop",
  },
  {
    id: "prom-2",
    officialId: "off-faisal-siddiqui",
    officialName: "Faisal Siddiqui",
    ucName: "UC-7 Gulshan",
    text: "Install reinforced concrete slabs on all 18 open manholes along school access lanes.",
    source: "Citizen Forum August 2026",
    dateMade: "2026-08-10",
    dueDate: "2026-10-15",
    status: "pending",
  },
  {
    id: "prom-3",
    officialId: "off-michael-masih",
    officialName: "Michael Masih",
    ucName: "UC-3 Essa Nagri",
    text: "Clear main commercial drain obstruction before monsoon onset.",
    source: "Election Campaign Manifesto",
    dateMade: "2026-05-10",
    dueDate: "2026-07-15",
    status: "broken",
  },
];

export const MOCK_POLLS: PollRecord[] = [
  {
    id: "poll-1",
    ucId: "uc-gulshan-7",
    ucName: "UC-7 Gulshan",
    title: "Which area should UC-7 road maintenance team prioritize next week?",
    options: [
      { id: "opt-1", text: "Service lane potholes outside Disco Bakery", votes: 89 },
      { id: "opt-2", text: "Block 13-A residential back streets", votes: 42 },
      { id: "opt-3", text: "Link road connecting University Road to Millennium", votes: 61 },
    ],
    totalVotes: 192,
    closesAt: "2026-09-30T23:59:00Z",
    isClosed: false,
    userVotedOptionId: undefined,
  },
  {
    id: "poll-2",
    ucId: "uc-gulshan-7",
    ucName: "UC-7 Gulshan",
    title: "Where should the newly allocated 20 solar streetlights be installed?",
    options: [
      { id: "opt-2a", text: "Block 13-D Family Park Perimeter", votes: 114 },
      { id: "opt-2b", text: "NIPA Chowrangi Pedestrian Crossings", votes: 98 },
      { id: "opt-2c", text: "Commercial Market Alley behind Bank Square", votes: 47 },
    ],
    totalVotes: 259,
    closesAt: "2026-10-05T23:59:00Z",
    isClosed: false,
    userVotedOptionId: undefined,
  },
  {
    id: "poll-3",
    ucId: "uc-gulshan-7",
    ucName: "UC-7 Gulshan",
    title: "Monsoon Preparedness: Which storm drain was the critical choke point?",
    options: [
      { id: "opt-3a", text: "NIPA Underpass culvert feeder (Cleared by UC team)", votes: 312 },
      { id: "opt-3b", text: "Block 13-C open drain crossing", votes: 142 },
    ],
    totalVotes: 454,
    closesAt: "2026-09-15T23:59:00Z",
    isClosed: true,
    userVotedOptionId: "opt-3a",
  },
];

export const MOCK_NGOS: NGO[] = [
  {
    id: "ngo-saylani",
    name: "Saylani Welfare International Trust",
    slug: "saylani-welfare",
    logo: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=120&h=120&fit=crop",
    registrationNumber: "REG-KHI-4019",
    focusCategories: ["drains", "water", "parks"],
    activeTowns: ["Gulshan Town", "Korangi Town", "Liaquatabad Town"],
    contactPhone: "021-111-729-526",
    contactEmail: "civic@saylaniwelfare.com",
    verifiedBadge: true,
    adoptedIssuesCount: 38,
    resolvedIssuesCount: 35,
    onTimeRate: 92,
    citizenThankYous: 412,
    impactRank: 1,
  },
  {
    id: "ngo-jdc",
    name: "JDC Foundation Pakistan",
    slug: "jdc-foundation",
    logo: "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=120&h=120&fit=crop",
    registrationNumber: "REG-KHI-2184",
    focusCategories: ["drains", "streets", "electricity"],
    activeTowns: ["Gulshan Town", "Jamshed Town", "Saddar Town"],
    contactPhone: "021-36341052",
    contactEmail: "action@jdcwelfare.org",
    verifiedBadge: true,
    adoptedIssuesCount: 29,
    resolvedIssuesCount: 27,
    onTimeRate: 93,
    citizenThankYous: 368,
    impactRank: 2,
  },
  {
    id: "ngo-fixit",
    name: "FixIt Pakistan",
    slug: "fixit-pakistan",
    logo: "https://images.unsplash.com/photo-1541888946425-d0fbb186f5f8?w=120&h=120&fit=crop",
    registrationNumber: "REG-KHI-8841",
    focusCategories: ["drains", "streets", "trash"],
    activeTowns: ["Gulshan Town", "Nazimabad Town", "North Nazimabad Town"],
    contactPhone: "0300-8201923",
    contactEmail: "contact@fixit.pk",
    verifiedBadge: true,
    adoptedIssuesCount: 45,
    resolvedIssuesCount: 41,
    onTimeRate: 91,
    citizenThankYous: 520,
    impactRank: 3,
  },
  {
    id: "ngo-shehri",
    name: "Shehri - Citizens for a Better Environment (CBE)",
    slug: "shehri-cbe",
    logo: "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=120&h=120&fit=crop",
    registrationNumber: "REG-KHI-1102",
    focusCategories: ["parks", "encroachment", "air_noise"],
    activeTowns: ["Gulshan Town", "Clifton Town", "Saddar Town"],
    contactPhone: "021-35860714",
    contactEmail: "info@shehri.org",
    verifiedBadge: true,
    adoptedIssuesCount: 18,
    resolvedIssuesCount: 16,
    onTimeRate: 88,
    citizenThankYous: 210,
    impactRank: 4,
  },
];

export const MOCK_COMMUNITY_LEADERS: CommunityLeader[] = [
  {
    id: "lead-hammad",
    userId: "user-hammad-1",
    ucId: "uc-gulshan-7",
    ucName: "UC-7 Gulshan (NIPA / Block 13)",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    realName: "Syed Hammad Raza",
    slug: "hammad-raza",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=240&h=240&fit=crop&crop=face",
    bio: "Civil engineering graduate & resident of Block 13-D. Working on open drains and street safety.",
    whyServe: "I grew up in Gulshan Block 13 and want to fix neighborhood infrastructure through practical community action before asking for a vote.",
    party: "Independent",
    plansToContest: "yes",
    identityVerified: true,
    identityVerifiedAt: "2026-08-10",
    status: "active",
    strikes: 0,
    score: 76.8,
    rankInUc: 1,
    rankInTown: 4,
    rankInCity: 22,
    trend30d: 5.4,
    hasEnoughData: true,
    activeAdoptionsCount: 8,
    resolvedCountLifetime: 12,
    onTimeRate: 92,
    eventsCount: 3,
    pledgesKept: 4,
    pledgesTotal: 4,
    thankYouCount: 168,
    fixSatisfaction: 4.8,
    teamMembers: [
      { id: "tm-1", name: "Danish Farooqi", role: "Site Coordinator" },
      { id: "tm-2", name: "Ayesha Noor", role: "Logistics" },
    ],
  },
  {
    id: "lead-kiran",
    userId: "user-kiran-2",
    ucId: "uc-gulshan-7",
    ucName: "UC-7 Gulshan (NIPA / Block 13)",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    realName: "Kiran Fatima",
    slug: "kiran-fatima",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=240&h=240&fit=crop&crop=face",
    bio: "Environmental lawyer & neighborhood advocate for Gulshan public parks and waste collection.",
    whyServe: "Dedicated to making municipal systems accountable and clearing toxic open waste dump sites.",
    party: "Independent",
    plansToContest: "yes",
    identityVerified: true,
    identityVerifiedAt: "2026-08-15",
    status: "active",
    strikes: 0,
    score: 71.2,
    rankInUc: 2,
    rankInTown: 8,
    rankInCity: 39,
    trend30d: 3.1,
    hasEnoughData: true,
    activeAdoptionsCount: 6,
    resolvedCountLifetime: 9,
    onTimeRate: 89,
    eventsCount: 2,
    pledgesKept: 3,
    pledgesTotal: 4,
    thankYouCount: 124,
    fixSatisfaction: 4.6,
    teamMembers: [
      { id: "tm-3", name: "Rehan Siddiqui", role: "Legal & Documentation" },
    ],
  },
  {
    id: "lead-bilal",
    userId: "user-bilal-3",
    ucId: "uc-gulshan-7",
    ucName: "UC-7 Gulshan (NIPA / Block 13)",
    townId: "town-gulshan",
    townName: "Gulshan Town",
    realName: "Muhammad Bilal Qureshi",
    slug: "bilal-qureshi",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=240&h=240&fit=crop&crop=face",
    bio: "Small business owner on University Road focusing on commercial alley lighting & security.",
    whyServe: "Serving our shopkeepers and pedestrians with transparent lighting and pothole fixes.",
    party: "Independent",
    plansToContest: "no",
    identityVerified: true,
    identityVerifiedAt: "2026-08-20",
    status: "active",
    strikes: 0,
    score: 64.5,
    rankInUc: 3,
    rankInTown: 14,
    rankInCity: 61,
    trend30d: -1.2,
    hasEnoughData: true,
    activeAdoptionsCount: 4,
    resolvedCountLifetime: 5,
    onTimeRate: 80,
    eventsCount: 1,
    pledgesKept: 2,
    pledgesTotal: 3,
    thankYouCount: 78,
    fixSatisfaction: 4.2,
    teamMembers: [],
  },
];

export const MOCK_AUDIT_LOG: AuditLogEntry[] = [
  {
    id: "aud-401",
    date: "2026-09-24 11:20 PKT",
    actor: "Moderation Engine & Admin Rule #4",
    action: "Brigading cluster neutralized",
    affectedUcOrOfficial: "UC-7 Gulshan",
    reason: "Identified 18 accounts created within 10 minutes from single IP subnet targeting 1 issue. Held votes at weight 0.0.",
  },
  {
    id: "aud-400",
    date: "2026-09-23 16:45 PKT",
    actor: "Admin (Jurisdiction Panel)",
    action: "Jurisdiction ruling published",
    affectedUcOrOfficial: "Issue #K-10294 (Main University Arterial)",
    reason: "Arterial road over 100ft width ruled as KMC/Town responsibility. Removed from UC-7 baseline score.",
  },
  {
    id: "aud-399",
    date: "2026-09-22 09:00 PKT",
    actor: "pg_cron Score Engine (v1.0.0)",
    action: "Scheduled 6-hour Score Recalculation",
    affectedUcOrOfficial: "All 246 Karachi UCs",
    reason: "Computed rolling 90-day Bayesian scores. Hash chained to block #2026-09-W4.",
  },
];
